app/urls.py
from django.views.generic import RedirectView
from django.urls import path, re_path,include
from app import views
from .views import userProfileView, UserLineSetting,Create_LineSetting,LineSettingUpdateView,LineSettingDeleteView

urlpatterns = [
    # Matches any html file 
    re_path('user-profile.html', userProfileView, name='user'),
    re_path("setting.html",UserLineSetting,name="LineSettings"),
    path('NewSetting', Create_LineSetting.as_view(), name="CreateLineSetting"),
    path('updateLineSetting/<int:pk>', LineSettingUpdateView.as_view(), name="updateLineSetting"),
    path('deleteLineSetting/<int:pk>', LineSettingDeleteView.as_view(), name="deleteLineSetting"),
    re_path(r'^.*\.html', views.pages, name='pages'),
    #re_path(r'dashboard/',RedirectView.as_view(url='/')),
    # The home page 
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from rest_framework.routers import DefaultRouter
from isplcAPI import views
from rest_framework.authtoken.views import obtain_auth_token
from core import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'isplcs', views.isplcViewSet)
router.register(r'devices', views.devicesViewSet)
router.register(r'token2auther', views.TokenAuthorView, basename='T4A')
router.register(r'GetControlContext', views.ControlContextView, basename='ControlContext')
router.register(r'GetLineToken', views.lineTokenView, basename='getlinetoken')
router.register(r'GetlineSetting', views.lineSettingView, basename='getlineSetting')
urlpatterns = [
    
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),  # <-- And here
    path("", include("app.urls")),
    path("", include("dashboard.urls")),
    re_path(r'^api/', include(router.urls)),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path('avatar/', include('avatar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

app/forms.py
from django import forms
from django.contrib.auth.models import User
from django import forms
from django.core.files.images import get_image_dimensions
from .models import LineModel,LineSettingsModel
from bootstrap_modal_forms.forms import BSModalForm

class UserProfile(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "username",                
                "class"       : "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class"       : "form-control"
            }
        ))
    class Meta:
        model = User
        fields = ('username','email') 

class UserLineForm(forms.ModelForm):
    LineToken = forms.CharField(
    widget=forms.TextInput(
        attrs={
            "placeholder" : "LineToken",                
            "class"       : "form-control"
        }
    ))

    class Meta:
        model = LineModel
        fields = ('LineToken',) 

class LineNsettingForm(BSModalForm): 

    def __init__(self, *args, **kwargs):
        author = kwargs['request'].user
        #['request']['user']['id']

        super(LineNsettingForm, self).__init__(*args, **kwargs)

        try:
            Setts = LineSettingsModel.objects.filter(author=author)
        except LineSettingsModel.DoesNotExist :
            Setts = []

        self.initial['author'] = author
        self.initial['Text'] = '-'

    class Meta:
        model = LineSettingsModel
        exclude = ['timestamp',]
        widgets = {
            'author': forms.HiddenInput(),
        }

class LineUsettingForm(BSModalForm): 

    def __init__(self, *args, **kwargs):
        #['request']['user']['id']
        super(LineUsettingForm, self).__init__(*args, **kwargs)

        
    class Meta:
        model = LineSettingsModel
        exclude = ['timestamp',]
        widgets = {
            'author': forms.HiddenInput(),
        }

core/templates/pages/CreatLineSetting.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">New Data</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    <div class="form-group type" >

    </div>
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" placeholder=field.label %}
        {% else %}
            {% render_field field class="form-control" placeholder=field.label %}
        {% endif %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <div class="invalid-feedback" style="display: block;">{{ error }}</div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

core/templates/pages/My_Device.html
{% extends "layouts/base-site.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Messages -->
<div id="myAlert">

</div>
<!-- End Messages -->


<div class="main-content-container container-fluid px-4">
  <!-- Page Header -->
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle">Dashboard</span>
      <h3 class="page-title"></h3>
    </div>
  </div>
  <!-- End Page Header -->
  <div class="row">
    
  </div>
 
  <div class="row">
    <div class="col">
      <div class="card card-small mb-4">
        <div class="card-header border-bottom">
          <h6 class="m-0">Devices</h6>
        </div>
        <div class="card-body p-0 pb-3 text-center">
          <table class="table mb-0">
            <thead class="bg-light">
              <tr>
                <th scope="col" class="border-0">#</th>
                <th scope="col" class="border-0">Device Name</th>
                <th scope="col" class="border-0">isPLC Count</th>
                <th scope="col" class="border-0">Device IP</th>
                <th scope="col" class="border-0">Update Time</th>
              </tr>
            </thead>
            <tbody>
              {% for device in devices%}
              <tr>
               
                <td>{{ forloop.counter }}</td>
                <td>{{ device.device_name }}</td>
                <td>{{ device.displc_count }}</td>
                <td>{{ device.device_IP }}</td>
                <td>{{ device.last_modify_date }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>



  
</div>


<script>

</script>


<style>
  .col-lg {
    list-style: none;
    float:left;
    padding: initial;
  }
  .ui-state-highlight{
    margin-left: 5rem;
    margin-right: 5rem;
  }
  .stats-small {
    width: 17.5rem;
  }
  p.indexlable {
    position: absolute;
    border: #a4b0be78 solid 1px;
    border-radius: 3px;
    margin: 4px;
    padding: 0px 4px 0px 4px;
    color: #a4b0be78;
  }

  .update-button {
    position: relative;
    text-align: right;
    z-index: 10;
    margin: -14px 8px -14px -14px;
    float: right;
    border-radius: 100%;
    font-size: 17px;
    padding: 0px 5px 0px 6px;
  }

  .delete-button {
    position: relative;
    text-align: right;
    z-index: 10;
    margin: 15px 8px -14px -14px;
    float: right;
    border-radius: 100%;
    font-size: 17px;
    padding: 0px 5px 0px 6px;
  }

  .tooltip {
    position: relative;
    display: inline-block;
    font-size: 16px;
  }

  .tooltip .tooltiptext {
    visibility: hidden;
    background-color: black;
    color: #fff;
    text-align: center;
    padding: 5px 0;
    border-radius: 6px;
    position: absolute;
    z-index: 1;
    width: 120px;
    top: 100%;
    left: 50%;
    margin-left: -60px;
    font-size: 12px;
  }

  .tooltip:hover .tooltiptext {
    visibility: visible;
  }
</style>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}


{% endblock javascripts %}

core/templates/pages/delete_lineSerring.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Line Settings</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete Line Setting with Name
      <strong>{{ LineSettingsModel.Name }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="delete-btn btn btn-danger">Delete</button>
  </div>

</form>

core/templates/pages/error-404.html
{% extends "layouts/base-site.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="error">

        <div class="error__content">
          <h2>404</h2>
          <h3>Something went wrong!</h3>
          <p>The page is not found. Please contact support.</p>
          <a href="/" class="btn btn-accent btn-pill">&larr; Go Home</a>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/pages/error-500.html
{% extends "layouts/base-site.html" %}

{% block title %} Page 500 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="error">

        <div class="error__content">
          <h2>500</h2>
          <h3>Something went wrong!</h3>
          <p>There was a problem on our end. Please try again later.</p>
          <a href="/" class="btn btn-accent btn-pill">&larr; Go Home</a>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/pages/logoutError-404.html
<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="shortcut icon" href="/static/assets/img/favicon.png" />

    <title>
        isPLC IoT - Page 404
    </title>
    
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="/static/assets/css/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="/static/assets/css/extras.1.1.0.min.css">
    <script async defer src="https://buttons.github.io/buttons.js"></script>

  </head>
  

 <!-- Specific Page CSS goes HERE  -->
 {% block stylesheets %}{% endblock stylesheets %}

 {% block content %}

    <div class="error">

        <div class="error__content">
          <h2>404</h2>
          <h3>Something went wrong!</h3>
          <p>The page is not found. Please contact support.</p>
          <a href="/" class="btn btn-accent btn-pill">&larr; Go Home</a>
        </div>

    </div>

 {% endblock content %}

 <!-- Specific Page JS goes HERE  -->
 {% block javascripts %}{% endblock javascripts %}


</html>

core/templates/pages/logoutError-500.html
<!doctype html>
<html class="no-js h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="shortcut icon" href="/static/assets/img/favicon.png" />

    <title>
      isPLC IoT - Page 500 
    </title>
    
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="/static/assets/css/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="/static/assets/css/extras.1.1.0.min.css">
    <script async defer src="https://buttons.github.io/buttons.js"></script>

  </head>

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="error">

        <div class="error__content"> 
          <h2>500</h2>
          <h3>Something went wrong!</h3>
          <p>There was a problem on our end. Please try again later.</p>
          <a href="/" class="btn btn-accent btn-pill">&larr; Go Home</a>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}
</html>

core/templates/pages/setting.html
{% extends "layouts/base-site.html" %}

{% block title %} Tester {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<link href="/static/assets/css/jquery.json-viewer.css" rel="stylesheet">

<!-- Messages -->
<div id="myAlert">

</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>
<!-- End Messages -->
<div>
  {% if messages %}
  {% for message in messages %}
  <div style="border-radius:0;" {% if message.tags %}
    class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
    <i class="fa fa-check mx-2"></i>
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif %}
</div>

<div class="main-content-container container-fluid px-4">

  <!-- Page Header -->
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle">Settings</span>
      <h3 class="page-title"></h3>
    </div>
  </div>
  <!-- End Page Header -->
  <div class="row">
    <div class="col-lg-8">
        <div class="card card-small mb-4">
          <div class="card-header border-bottom">
            <h6 class="m-0">Line Bot Setting</h6>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item p-3">
              <div class="row">


                <div class="col">
                    <div class='container'>   
                        <form method="post">    
                            {% csrf_token %}    
                            <div class="col-md-6">
                              <label for="fePassword">Token </label>
                              
                              <input type="text" name="LineToken" placeholder="LineToken" class="form-control" required="" id="id_LineToken" value="">
                            </div>
                            <br>
                            <button class="post2 btn btn-info mt-1" type="submit">Submit</button>  
                        </form>
                    </div>
                </div>

              </div>
            </li>
          </ul>
        </div>
      </div>
  </div>
 
  <div class="row">
    
  </div>

  <div class="row">
    <div class="col">
      <div class="card card-small mb-4">
        <div class="card-header border-bottom" style="padding-bottom: 0;">
          <h6 class="m-0"style="text-align: left; float: left;display: inline;">Line Function Setting</h6>
          <button type="button" class="create-setting mb-2 btn btn-sm btn-info mr-1"style="float: right;text-align: right;display: inline;"> <i class="material-icons" style="font-size: x-large;">add_box</i></button>
        </div>
        
        <div class="card-body p-0 pb-3 text-center">
          <table class="table mb-0">
            <thead class="bg-light">
              <tr>
                <th scope="col" class="border-0">#</th>
                <th scope="col" class="border-0">Message Type</th>
                <th scope="col" class="border-0">Title</th>
                <th scope="col" class="border-0">button1 Text</th>
                <th scope="col" class="border-0">button2 Text</th>
                <th scope="col" class="border-0">isPLC ID</th>
                <th scope="col" class="border-0">Coil Type</th>
                <th scope="col" class="border-0">Coil ID</th>
                <th scope="col" class="border-0">Edit</th>
                <th scope="col" class="border-0">Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for Lsettings in lineSetting%}
              <tr>
               
                <td>{{ forloop.counter }}</td>

                {% if Lsettings.msgType == 1 %}
                <td>Button</td>
                {% else %}
                <td>Notify</td>
                {% endif %}

                <td>{{ Lsettings.msgContext }}</td>
                <td>{{ Lsettings.button1 }}</td>
                <td>{{ Lsettings.button2 }}</td>
                <td>{{ Lsettings.isPLC_ID }}</td>

                {% if Lsettings.Contact_Type == 1 %}
                <td>Y</td>
                {% else %}
                <td>M</td>
                {% endif %}

                <td>{{ Lsettings.Contact_ID }}</td>
                <td>
                  <button type="button" class="update-button btn btn-sm btn-primary RowButton" data-id="{% url 'updateLineSetting' Lsettings.pk %}" >
                          <i class="material-icons">edit</i>
                  </button>
                </td>
                <td>
                  <button type="button" class="delete-button btn btn-sm btn-danger RowButton" data-id="{% url 'deleteLineSetting' Lsettings.pk %}" >
                          <i class="material-icons">delete_forever</i>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


  
</div>


<script>
  $(document).ready(function () {
    $(".create-setting").modalForm({
      formURL: "{% url 'CreateLineSetting' %}"
    });
    $(".update-button").each(function () {
      $(this).modalForm({ formURL: $(this).data('id') });
    });
    $(".delete-button").each(function () {
      $(this).modalForm({ formURL: $(this).data('id') });
    })
    $(".alert").fadeTo(2000, 500).slideUp(500, function () {
      $(".alert").slideUp(500);
    });

  });
</script>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}


{% endblock javascripts %}

core/templates/pages/test.html
{% extends "layouts/base-site.html" %}

{% block title %} Tester {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


<link href="/static/assets/css/jquery.json-viewer.css" rel="stylesheet">

<!-- Messages -->
<div id="myAlert">

</div>
<!-- End Messages -->


<div class="main-content-container container-fluid px-4">
  <!-- Page Header -->
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle">Tester Center</span>
      <h3 class="page-title"></h3>
    </div>
  </div>
  <!-- End Page Header -->
  <div class="row">
    <!-- Input & Button Groups -->
    <div class="card card-small mb-4 ml-5">
      <div class="card-header border-bottom">
        <h6 class="m-0">WebSocket Test</h6>
      </div>  
      <ul class="list-group list-group-flush">
        <div class="row ml-1 mr-5">
        <li class="list-group-item px-3">
          <form>
            <!-- Input Groups -->
            <div class="input-group mb-3">
              <input type="text" class="wsUrl form-control" placeholder="ws://" aria-label="ws://" aria-describedby="basic-addon1"> 
              <div class="input-group-append">
                <button class="wsOpenbtn btn btn-white" type="button">Open</button>
              </div>
            </div>
            <div class="input-group mb-3">
              <textarea cols="40" rows="5" class="wsSendMessage form-control" placeholder="contact" aria-label="contact" aria-describedby="basic-addon2"></textarea> 
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <button class="wsSendbtn btn btn-white" type="button">Send</button>
                <button class="btn btn-white" id="btn-json-viewer" type="button">json-viewer</button>
              </div>
            </div>
            <!-- Input Groups -->
            <!-- Seamless Input Groups -->
            <strong class="text-muted d-block mb-2">Receive</strong>
            <div class="input-group mb-3">
              <textarea cols="40" rows="5" class="wsReceiveMessage form-control" placeholder="contact" aria-label="contact" aria-describedby="basic-addon2"></textarea> 
            </div>
            <!-- Input/Button Group -->

            <!-- / Input/Button Group -->
          </form>
        
        </li>
        <li>
          
          <pre id="json-viewer"></pre>
          <script>
            $(".wsReceiveMessage").bind('input propertychange', function() {
              JV()
            });
            function JV(){
              var val = $(".wsReceiveMessage").val()
              console.log(val);
              try {
                var input = eval('(' + $(".wsReceiveMessage").val() + ')');
                $('#json-viewer').jsonViewer(input);
              }
              catch (error) {
                alert("Cannot eval JSON: " + error);
              }
            }
          </script>
        </li>

        
      </div>
      </ul>
    </div>
    <!-- / Input & Button Groups -->
  </div>
 
  <div class="row">
    
  </div>



  
</div>

<script>
  $(document).ready(function () {
    $(".wsUrl").val('ws://' + window.location.host + '/ws/Client/View/1')
  });

  $(".wsOpenbtn").click( function( event ) {
    intiWebSocket($(".wsUrl").val());
  });

  

  function showAlert(lable,msg){
      if($("#myAlert").find("div#myAlert2").length==0){
        var Adata = "<div style='border-radius:0;' class='alert alert-icon alert-"+ lable + " alert-dismissible fade show mb-0' role='alert' id='myAlert2'> <i class='fa fa-info mx-2'></i> "+ msg +" <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>"
        $("#myAlert").append(Adata);
      }
      $(".alert").fadeTo(4000, 500).slideUp(500, function(){
      $(".alert").slideUp(500);
      $(".alert").remove()
    })};

  function intiWebSocket(url) {
    $(".reconnectbutton").attr('disabled', true);
    $(".wsSendbtn").click(function(ev){
      sendMsg($(".wsSendMessage").val());
    });
    
    var ClientSocket = new WebSocket(url);

    ClientSocket.onmessage = function(e) {
      var data = JSON.parse(e.data);
      var message = data['message'];
      console.log(message + '\n');
      $(".wsReceiveMessage").val(message)
      JV()
    };

    ClientSocket.onopen = function(e){
      $(".reconnectbutton").attr('disabled', false);
      showAlert('success','Successfully connected to the server!');
    };

    ClientSocket.onclose = function(e) {
      $(".reconnectbutton").attr('disabled', false);
      showAlert('warning','Client socket closed unexpectedly');
      console.error('Client socket closed unexpectedly');
    };
    function sendMsg(msg){
      ClientSocket.send(msg);
    }
  };
</script>


<style>
  .col-lg {
    list-style: none;
    float:left;
    padding: initial;
  }
  .ui-state-highlight{
    margin-left: 5rem;
    margin-right: 5rem;
  }
  .stats-small {
    width: 17.5rem;
  }
  p.indexlable {
    position: absolute;
    border: #a4b0be78 solid 1px;
    border-radius: 3px;
    margin: 4px;
    padding: 0px 4px 0px 4px;
    color: #a4b0be78;
  }

  .update-button {
    position: relative;
    text-align: right;
    z-index: 10;
    margin: -14px 8px -14px -14px;
    float: right;
    border-radius: 100%;
    font-size: 17px;
    padding: 0px 5px 0px 6px;
  }

  .delete-button {
    position: relative;
    text-align: right;
    z-index: 10;
    margin: 15px 8px -14px -14px;
    float: right;
    border-radius: 100%;
    font-size: 17px;
    padding: 0px 5px 0px 6px;
  }

  .tooltip {
    position: relative;
    display: inline-block;
    font-size: 16px;
  }

  .tooltip .tooltiptext {
    visibility: hidden;
    background-color: black;
    color: #fff;
    text-align: center;
    padding: 5px 0;
    border-radius: 6px;
    position: absolute;
    z-index: 1;
    width: 120px;
    top: 100%;
    left: 50%;
    margin-left: -60px;
    font-size: 12px;
  }

  .tooltip:hover .tooltiptext {
    visibility: visible;
  }
</style>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}


{% endblock javascripts %}

core/templates/pages/update_LineSetting.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Line Setting</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" placeholder=field.label %}
        {% else %}
            {% render_field field class="form-control" placeholder=field.label %}
        {% endif %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <div class="invalid-feedback" style="display: block;">{{ error }}</div>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Update</button>
  </div>

</form>

<script>
  
</script>